[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_KEY="AIzaSyCdoEH47gZlm21kJvKsfYKCAkViffdwJ9k"
  REACT_APP_AUTH_DOMAIN="ihostmn-6b447.firebaseapp.com"
  REACT_APP_PROJECT_ID="ihostmn-6b447"
  REACT_APP_STORAGE_BUCKET="ihostmn-6b447.appspot.com"
  REACT_APP_MESSAGING_SENDER_ID="188380464532"
  REACT_APP_APP_ID="1:188380464532:web:9a9d8b8f1811ecac2ebb81"
